# Generated by Django 5.1.6 on 2025-02-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_route',
            field=models.CharField(default='/cafe.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
